"""metadata united

Revision ID: 22baedca654d
Revises: 9ac6669bc97e
Create Date: 2023-07-24 15:17:31.471935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22baedca654d'
down_revision = '9ac6669bc97e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('match_res')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_res',
    sa.Column('min_kills', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('max_deaths', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('min_assists', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('max_kills', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('min_deaths', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('max_assists', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('role_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='role_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('registered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='user_role_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_table('match',
    sa.Column('game_duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('match_id', sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
