"""ADD match 2

Revision ID: 9bf07c863ee6
Revises: 0c541fd26e1f
Create Date: 2023-07-22 14:17:19.228915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf07c863ee6'
down_revision = '0c541fd26e1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
