"""metadata = [metadata_auth, metadata_lol]

Revision ID: 9d5dea2a9ff3
Revises: 762bf2ce25e5
Create Date: 2023-07-22 14:25:35.526366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5dea2a9ff3'
down_revision = '762bf2ce25e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
